name: Assertions and Static Report

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * 1/3 # Every Monday and Thursday at 7am UTC

jobs:
  assertions-and-static-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer wrangler

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site unjs.io --budget 75 --build-static

      - run: wrangler pages deploy .unlighthouse --branch=main --commit-dirty --project-name inspect-unjs-website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
