name: Assertions and Static Report

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * 1/3 # Every Monday and Thursday at 7am UTC

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer wrangler

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site unjs.io --budget 75 --build-static

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./.unlighthouse

  deploy:
    needs: build-report
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@ee48c7b82e077d7b8ef30b50a719e6a792a50c9a # v2
